[2024-05-09T21:13:14.603+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T21:13:12.118921+00:00 [queued]>
[2024-05-09T21:13:14.625+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T21:13:12.118921+00:00 [queued]>
[2024-05-09T21:13:14.626+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-09T21:13:14.693+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_minio> on 2024-05-09 21:13:12.118921+00:00
[2024-05-09T21:13:14.706+0000] {standard_task_runner.py:57} INFO - Started process 8426 to run task
[2024-05-09T21:13:14.734+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pyspark_dag', 'pyspark_minio', 'manual__2024-05-09T21:13:12.118921+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark.py', '--cfg-path', '/tmp/tmp92be241i']
[2024-05-09T21:13:14.750+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask pyspark_minio
[2024-05-09T21:13:14.938+0000] {task_command.py:416} INFO - Running <TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T21:13:12.118921+00:00 [running]> on host ae2eea95888a
[2024-05-09T21:13:15.141+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_dag' AIRFLOW_CTX_TASK_ID='pyspark_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T21:13:12.118921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T21:13:12.118921+00:00'
[2024-05-09T21:13:15.187+0000] {docker.py:343} INFO - Starting docker container from image wba-demo/spark:latest
[2024-05-09T21:13:15.193+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-05-09T21:13:15.755+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:13:15.75 [0m[38;5;2mINFO [0m ==>
[2024-05-09T21:13:15.756+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:13:15.75 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2024-05-09T21:13:15.757+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:13:15.75 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2024-05-09T21:13:15.759+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:13:15.75 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2024-05-09T21:13:15.760+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:13:15.76 [0m[38;5;2mINFO [0m ==>
[2024-05-09T21:13:15.768+0000] {docker.py:413} INFO - 
[2024-05-09T21:13:19.224+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-05-09T21:13:19.364+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2024-05-09T21:13:19.371+0000] {docker.py:413} INFO - io.delta#delta-core_2.12 added as a dependency
[2024-05-09T21:13:19.372+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-05-09T21:13:19.373+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-4af5314a-8afa-439e-a26c-69a21d4dc020;1.0
	confs: [default]
[2024-05-09T21:13:20.005+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.010+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.018+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.021+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.044+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.046+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.051+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.054+0000] {docker.py:413} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-05-09T21:13:20.109+0000] {docker.py:413} INFO - :: resolution report :: resolve 735ms :: artifacts dl 0ms
[2024-05-09T21:13:20.110+0000] {docker.py:413} INFO - :: modules in use:
[2024-05-09T21:13:20.110+0000] {docker.py:413} INFO - ---------------------------------------------------------------------
[2024-05-09T21:13:20.111+0000] {docker.py:413} INFO - |                  |            modules            ||   artifacts   |
[2024-05-09T21:13:20.111+0000] {docker.py:413} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
[2024-05-09T21:13:20.112+0000] {docker.py:413} INFO - |      default     |   2   |   0   |   0   |   0   ||   0   |   0   |
	---------------------------------------------------------------------
[2024-05-09T21:13:20.117+0000] {docker.py:413} INFO - :: problems summary ::
[2024-05-09T21:13:20.117+0000] {docker.py:413} INFO - :::: WARNINGS
	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.pom

	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar

	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.pom

	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar
[2024-05-09T21:13:20.118+0000] {docker.py:413} INFO - module not found: io.delta#delta-core_2.12;2.4.0

	==== local-m2-cache: tried

	  file:/opt/bitnami/spark/.m2/repository/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.pom

	  -- artifact io.delta#delta-core_2.12;2.4.0!delta-core_2.12.jar:

	  file:/opt/bitnami/spark/.m2/repository/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar

	==== local-ivy-cache: tried
[2024-05-09T21:13:20.119+0000] {docker.py:413} INFO - /opt/bitnami/spark/.ivy2/local/io.delta/delta-core_2.12/2.4.0/ivys/ivy.xml

	  -- artifact io.delta#delta-core_2.12;2.4.0!delta-core_2.12.jar:

	  /opt/bitnami/spark/.ivy2/local/io.delta/delta-core_2.12/2.4.0/jars/delta-core_2.12.jar

	==== central: tried

	  https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.pom

	  -- artifact io.delta#delta-core_2.12;2.4.0!delta-core_2.12.jar:
[2024-05-09T21:13:20.120+0000] {docker.py:413} INFO - https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar

	==== spark-packages: tried

	  https://repos.spark-packages.org/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.pom

	  -- artifact io.delta#delta-core_2.12;2.4.0!delta-core_2.12.jar:

	  https://repos.spark-packages.org/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar

	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.pom
[2024-05-09T21:13:20.120+0000] {docker.py:413} INFO - Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar

	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.pom

	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar

		module not found: org.apache.hadoop#hadoop-aws;3.3.6

	==== local-m2-cache: tried

	  file:/opt/bitnami/spark/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.pom
[2024-05-09T21:13:20.120+0000] {docker.py:413} INFO - -- artifact org.apache.hadoop#hadoop-aws;3.3.6!hadoop-aws.jar:

	  file:/opt/bitnami/spark/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar

	==== local-ivy-cache: tried

	  /opt/bitnami/spark/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.6/ivys/ivy.xml

	  -- artifact org.apache.hadoop#hadoop-aws;3.3.6!hadoop-aws.jar:
[2024-05-09T21:13:20.121+0000] {docker.py:413} INFO - /opt/bitnami/spark/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.6/jars/hadoop-aws.jar

	==== central: tried

	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.pom

	  -- artifact org.apache.hadoop#hadoop-aws;3.3.6!hadoop-aws.jar:

	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar

	==== spark-packages: tried
[2024-05-09T21:13:20.121+0000] {docker.py:413} INFO - https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.pom

	  -- artifact org.apache.hadoop#hadoop-aws;3.3.6!hadoop-aws.jar:

	  https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::
[2024-05-09T21:13:20.122+0000] {docker.py:413} INFO - :: io.delta#delta-core_2.12;2.4.0: not found

		:: org.apache.hadoop#hadoop-aws;3.3.6: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-05-09T21:13:20.122+0000] {docker.py:413} INFO - Exception in thread "main"
[2024-05-09T21:13:20.122+0000] {docker.py:413} INFO - java.lang.RuntimeException: [unresolved dependency: io.delta#delta-core_2.12;2.4.0: not found, unresolved dependency: org.apache.hadoop#hadoop-aws;3.3.6: not found]
[2024-05-09T21:13:20.122+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1528)
[2024-05-09T21:13:20.123+0000] {docker.py:413} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:332)
[2024-05-09T21:13:20.123+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-05-09T21:13:20.123+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-05-09T21:13:20.490+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.43/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.43/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmprmn9rvau")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-05-09T21:13:20.497+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_dag, task_id=pyspark_minio, execution_date=20240509T211312, start_date=20240509T211314, end_date=20240509T211320
[2024-05-09T21:13:20.545+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task pyspark_minio (Docker container failed: {'StatusCode': 1}; 8426)
[2024-05-09T21:13:20.581+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-09T21:13:20.639+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
