[2024-05-09T23:15:18.287+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T23:15:15.946612+00:00 [queued]>
[2024-05-09T23:15:18.302+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T23:15:15.946612+00:00 [queued]>
[2024-05-09T23:15:18.302+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-09T23:15:18.329+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_minio> on 2024-05-09 23:15:15.946612+00:00
[2024-05-09T23:15:18.339+0000] {standard_task_runner.py:57} INFO - Started process 886 to run task
[2024-05-09T23:15:18.344+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pyspark_dag', 'pyspark_minio', 'manual__2024-05-09T23:15:15.946612+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark.py', '--cfg-path', '/tmp/tmp0exg79bx']
[2024-05-09T23:15:18.347+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask pyspark_minio
[2024-05-09T23:15:18.424+0000] {task_command.py:416} INFO - Running <TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T23:15:15.946612+00:00 [running]> on host b2123672b907
[2024-05-09T23:15:18.602+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_dag' AIRFLOW_CTX_TASK_ID='pyspark_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T23:15:15.946612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T23:15:15.946612+00:00'
[2024-05-09T23:15:18.646+0000] {docker.py:470} INFO - Pulling docker image wba-demo/spark:latest
[2024-05-09T23:15:21.914+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://docker-proxy:2375/v1.43/images/create?tag=latest&fromImage=wba-demo%2Fspark

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 472, in execute
    for output in self.cli.pull(self.image, stream=True, decode=True):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http://docker-proxy:2375/v1.43/images/create?tag=latest&fromImage=wba-demo%2Fspark: Not Found ("pull access denied for wba-demo/spark, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
[2024-05-09T23:15:21.947+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_dag, task_id=pyspark_minio, execution_date=20240509T231515, start_date=20240509T231518, end_date=20240509T231521
[2024-05-09T23:15:21.994+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 67 for task pyspark_minio (404 Client Error for http://docker-proxy:2375/v1.43/images/create?tag=latest&fromImage=wba-demo%2Fspark: Not Found ("pull access denied for wba-demo/spark, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"); 886)
[2024-05-09T23:15:22.055+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-09T23:15:22.130+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
